services:
  - type: web
    name: fitai-backend
    env: python
    rootDir: Codigos/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fitai_db # Substitua pelo nome do seu banco de dados no Render
          property: internalConnectionString
      - key: SECRET_KEY
        generateValue: true # O Render pode gerar um valor seguro para você
      - key: GOOGLE_API_KEY
        value: AIzaSyD6SPq7hcAQVxtP3rv9s0wxFQpAql4c3gM # Adicione sua chave aqui
    preDeployCommand: alembic upgrade head
    disk:
      name: media-cache
      mountPath: /var/tmp/media
      sizeGB: 1 # Tamanho do disco persistente para caches, se necessário
    healthCheckPath: /healthz # Exemplo, ajuste se tiver um endpoint de health check
    autoDeploy: true
    numInstances: 1
    # Adicione os pacotes de sistema aqui
    build:
      pythonVersion: 3.9.x # Ou a versão exata do Python que você está usando, ex: 3.10.x, 3.11.x
      systemPackages:
        - libgl1-mesa-glx
        - libsm6
        - libxext6
        - libxrender1
